name: markerlessa
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<4.0
  - numpy>=2.1.2,<3.0
  - pandas>=2.2.3,<3.0
  - scipy>=1.14.1,<2.0
  - matplotlib>=3.9.2,<4.0
  - jupyter>=1.1.1,<2.0
  - ipympl>=0.9.4,<0.10.0
  - urllib3=1.26.15  # keeping exact since you specified exact in Poetry
  - pyqt>=6.7.1,<7.0
  - statsmodels>=0.14.4,<0.15.0
  - pip
  - pip:
    - trc-data-reader>=0.3.4,<0.4.0
    - colour>=0.1.5,<0.2.0
